### ISSUE TITLE
Advent Calendar 2016

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/advent-calendar#30]
- [x] Day 1: Another year of Dancing
- [x] Day 2: State of the Ecosystem
- [x] Day 3: Medium-Scale Dancer (part 1)
- [x] Day 4: Medium-Scale Dancer (part 2)
- [x] Day 5: Medium-Scale Dancer (part 3)
- [x] Day 6: Medium-Scale Dancer (part 4)
- [x] Day 7: Medium-Scale Dancer (part 5)
- [x] Day 8: Automatic restarts
- [x] Day 9: New parameters
- [x] Day 10: Exception handling, error logging and user messages made easy
- [x] Day 11: Dancer I18N with `Log::Report`
- [x] Day 12: How to speed up Dancer2 PT. 1
- [x] Day 13: How to speed up Dancer2 PT. 2
- [x] Day 14: How to speed up Dancer2 PT. 3
- [x] Day 15: How to speed up Dancer2 PT. 4
- [x] Day 16: How to speed up Dancer2 PT. 5
- [x] Day 17: Configuring your Dancer Apps
- [x] Day 18: Asynchronous Dancer2
- [x] Day 19: Changing your session ID
- [x] Day 20: `send_as` keyword
- [x] Day 21: Reducing boilerplate and managing exports in Dancer2
- [x] Day 22: New plugin architecture
- [x] Day 23: How to avoid XSS issues easily
- [x] Day 24: Contributing to Dancer2 (@cromedome)

Ideas:
- Supporting 304 Not Modified.
- D2P2.
- Searching with multiple fields and pagination.
- [Odds and ends](#32).

**Comment by SysPete** [comment]
I've add #31 as the basis of a change_session_id article. Still needs some love.
